SQLPatterns = {}
SQLPatterns.sendPly 		= "INSERT INTO players (`steamid`, `steamid64`, `usergroup`, `firstjoined`) VALUES(?, ?, ?, ?)"
SQLPatterns.selPly 			= "SELECT * FROM players WHERE `steamid` = ?"
SQLPatterns.sendLog			= "INSERT INTO log (`time`,`entry`) VALUES (?, ?)"
SQLPatterns.getpending 		= "SELECT * FROM pending WHERE `status` = 0 AND `addedon` < ?"
SQLPatterns.updatePStatus 	= "UPDATE pending SET `status` = 1 WHERE `id` = ?"
SQLPatterns.addPending		= "INSERT INTO pending (`steamid64`, `addedon`, `type`, `addargs` ) VALUES (?, ?, ?, ?)"
SQLPatterns.checkPending	= "SELECT * FROM pending WHERE `steamid64` = ? AND `addedon` > ? AND `status` = 0 AND `type` = ? AND `addargs` = ?"
SQLPatterns.updatePending	= "UPDATE pending SET `addedon` = ? WHERE `id` = ?"
SQLPatterns.updateUGroup	= "UPDATE players SET `usergroup` = ? WHERE `steamid64` = ?"
SQLPatterns.updatePWeps		= "UPDATE players SET `permaweapons` = ? WHERE `steamid64` = ?"